### ISSUE TITLE
Traceback when changing date of gathering

### ISSUE THREAD

**Issue by sdgathman** [ssbc/patchbay#125]
The date change is actually published, but then an error tab pops up with this:
```
TypeError: Cannot read property 'minDate' of undefined
    at isEnabled (/home/stuart/src/patchbay/node_modules/flatpickr/dist/flatpickr.js:921:18)
    at /home/stuart/src/patchbay/node_modules/flatpickr/dist/flatpickr.js:1367:32
    at Array.filter (native)
    at setSelectedDate (/home/stuart/src/patchbay/node_modules/flatpickr/dist/flatpickr.js:1366:43)
    at Flatpickr.setDate (/home/stuart/src/patchbay/node_modules/flatpickr/dist/flatpickr.js:1378:3)
    at Array.startDateTime (/home/stuart/src/patchbay/node_modules/patch-gatherings/gathering/html/startDateTime.js:44:42)
    at Observable.observable.set (/home/stuart/src/patchbay/node_modules/mutant/value.js:12:25)
    at /home/stuart/src/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/stuart/src/patchbay/node_modules/pull-stream/throughs/map.js:19:9
    at /home/stuart/src/patchbay/node_modules/pull-stream/throughs/map.js:19:9
```

**Comment by christianbundy** [comment]
I can verify that this is still happening on 7.14.0. The stack trace is slightly different now, but the error is the same:

```
TypeError: Cannot read property 'minDate' of undefined
    at isEnabled (/opt/patchbay-git/node_modules/flatpickr/dist/flatpickr.js:921:19)
    at /opt/patchbay-git/node_modules/flatpickr/dist/flatpickr.js:1367:32
    at Array.filter (<anonymous>)
    at setSelectedDate (/opt/patchbay-git/node_modules/flatpickr/dist/flatpickr.js:1366:43)
    at Flatpickr.setDate (/opt/patchbay-git/node_modules/flatpickr/dist/flatpickr.js:1378:3)
    at Array.startDateTime (/opt/patchbay-git/node_modules/patch-gatherings/gathering/html/startDateTime.js:43:42)
    at Observable.observable.set (/opt/patchbay-git/node_modules/mutant/value.js:12:25)
    at /opt/patchbay-git/node_modules/pull-stream/sinks/drain.js:24:37
    at /opt/patchbay-git/node_modules/pull-stream/throughs/map.js:19:9
    at /opt/patchbay-git/node_modules/pull-stream/throughs/map.js:19:9
    at /opt/patchbay-git/node_modules/pull-stream/throughs/filter.js:17:11
    at /opt/patchbay-git/node_modules/pull-stream/throughs/filter.js:17:11
    at callback (/opt/patchbay-git/node_modules/pull-pushable/index.js:84:5)
    at Function.push (/opt/patchbay-git/node_modules/pull-pushable/index.js:44:7)
    at notify (/opt/patchbay-git/node_modules/pull-notify/index.js:10:20)
    at /opt/patchbay-git/node_modules/pull-stream/sinks/drain.js:24:37
```
