### ISSUE TITLE
Cannot read property 'stream' of undefined

### ISSUE THREAD

**Issue by evbogue** [ssbc/patchbay#130]
I'm getting this error upon starting Patchbay using `npm start`. The feed doesn't load, Patchbay is unresponsive.

```
Cannot read property 'stream' of undefined
TypeError: Cannot read property 'stream' of undefined
    at api.sbot.pull.stream.sbot (/home/ev/patchbay/node_modules/patchcore/contact/obs.js:54:49)
    at /home/ev/patchbay/node_modules/patchcore/sbot.js:212:28
    at Array.watch (/home/ev/patchbay/node_modules/mutant/once-true.js:8:7)
    at Function.Observable.observable.set (/home/ev/patchbay/node_modules/mutant/value.js:12:25)
    at /home/ev/patchbay/node_modules/patchcore/sbot.js:75:18
    at /home/ev/patchbay/node_modules/ssb-client/index.js:105:5
    at next (/home/ev/patchbay/node_modules/multiserver/compose.js:28:14)
    at /home/ev/patchbay/node_modules/multiserver/compose.js:34:9
    at _cb (/home/ev/patchbay/node_modules/multiserver/plugins/shs.js:31:11)
    at /home/ev/patchbay/node_modules/secret-handshake/protocol.js:120:7
```

**Comment by evbogue** [comment]
I think I was getting this error because sbot was running in another window. I resolved it by quitting sbot.

However, now patchbay is not loading a stream. It does say that it is connected.

**Comment by dominictarr** [comment]
this happens because some needed plugins are not installed probably ssb-private

**Comment by dominictarr** [comment]
or ssb-backlinks
