### ISSUE TITLE
ssb-chess crashes

### ISSUE THREAD

**Issue by arj03** [ssbc/patchbay#156]
Navigating to /chess gives me the following error:

Uncaught (in promise) TypeError: Cannot read property 'pendingChallengesReceived' of undefined
    at Promise (/home/chrx/dev/patchbay/node_modules/ssb-chess/db/game_db.js:20:25)
    at Promise (<anonymous>)
    at Object.pendingChallengesReceived (/home/chrx/dev/patchbay/node_modules/ssb-chess/db/game_db.js:19:12)
    at Object.pendingChallengesReceived [as countUpdateFn] (/home/chrx/dev/patchbay/node_modules/ssb-chess/ctrl/game.js:44:19)
    at navItems.map.item (/home/chrx/dev/patchbay/node_modules/ssb-chess/ui/pageLayout/navigation.js:87:72)
    at Array.map (native)
    at updateCounts (/home/chrx/dev/patchbay/node_modules/ssb-chess/ui/pageLayout/navigation.js:87:34)
    at Object.oncreate (/home/chrx/dev/patchbay/node_modules/ssb-chess/ui/pageLayout/navigation.js:106:7)
    at Object.render (/home/chrx/dev/patchbay/node_modules/mithril/mithril.js:960:50)
    at run0 (/home/chrx/dev/patchbay/node_modules/mithril/mithril.js:1019:19)

npm ls ssb-chess gives me 1.7.1

**Comment by Happy0** [comment]
Thanks @arj03 .

Are you using your own scuttlebot instance, by any chance, rather than the one patchbay spins up internally by default?

**Comment by arj03** [comment]
I am :)

I'm running patchbay in dev mode, so with my own sbot server. I thought it might be because I needed to install the ssb-chess-db module in sbot, but if I do that I get:

/home/chrx/dev/scuttlebot/plugins/plugins.js:187
    throw new Error('plugin at:'+module_name+' expected name:'+name+' but had:'+(plugin||{}).name)
    ^

Error: plugin at:ssb-chess-db expected name:chess-db but had:ssbChessIndex
at Object.module.exports.loadUserPlugins (/home/chrx/dev/scuttlebot/plugins/plugins.js:187:15)

**Comment by Happy0** [comment]
Hmm.. I wonder if that's because I used a different name for `exports.name` compared to the name passed in to the `flumeUse` function in my plugin... :S

` https://github.com/Happy0/ssb-chess-db/blob/master/index.js `

**Comment by arj03** [comment]
Sure thing, just tell me how to test :)

**Comment by Happy0** [comment]
How are you installing the plugin? When I use

`scuttlebot plugins.install ssb-chess-db`

I get the following error:

`Command not found: plugins.install`

Am I using the wrong command? Or do I maybe need to reinstall scuttlebot or something?

**Comment by arj03** [comment]
sbot  plugins.install ssb-chess-db

**Comment by arj03** [comment]
README has been updated with instructions on how to get this working
