### ISSUE TITLE
Crash on middle click

### ISSUE THREAD

**Issue by ph1l** [ssbc/patchbay#157]
patchbay reliably crashes on middle click:

```
ssb@x61s-4280:~$ ./patchbay.sh 

> patchbay@7.12.2 dev /home/ssb/code/patchbay
> echo 'run your own sbot!' && electro main.js -- --title patchbay

run your own sbot!
BrowserWindow {
  _events: 
   { blur: [Function],
     focus: [Function],
     show: [Function: visibilityChanged],
     hide: [Function: visibilityChanged],
     minimize: [Function: visibilityChanged],
     maximize: [Function: visibilityChanged],
     restore: [Function: visibilityChanged] },
  _eventsCount: 7,
  devToolsWebContents: [Getter] }
{ clipboard: [Getter],
  crashReporter: [Getter],
  nativeImage: [Getter],
  shell: [Getter],
  app: [Getter],
  autoUpdater: [Getter],
  BrowserView: [Getter],
  BrowserWindow: [Getter],
  contentTracing: [Getter],
  dialog: [Getter],
  globalShortcut: [Getter],
  ipcMain: [Getter],
  Menu: [Getter],
  MenuItem: [Getter],
  net: [Getter],
  Notification: [Getter],
  powerMonitor: [Getter],
  powerSaveBlocker: [Getter],
  protocol: [Getter],
  screen: [Getter],
  session: [Getter],
  systemPreferences: [Getter],
  TouchBar: [Getter],
  Tray: [Getter],
  webContents: [Getter] }
/home/ssb/code/patchbay/node_modules/electro/index.js:83
    shell.openExternal(url)
    ^

ReferenceError: shell is not defined
    at WebContents.<anonymous> (/home/ssb/code/patchbay/node_modules/electro/index.js:83:5)
    at emitMany (events.js:146:13)
    at WebContents.emit (events.js:223:7)
    at EventEmitter.<anonymous> (/home/ssb/code/patchbay/node_modules/electron/dist/resources/electron.asar/browser/guest-window-manager.js:245:16)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7)
    at WebContents.webContents.on (/home/ssb/code/patchbay/node_modules/electron/dist/resources/electron.asar/browser/api/browser-window.js:30:13)
    at emitMany (events.js:146:13)
    at WebContents.emit (events.js:223:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! patchbay@7.12.2 dev: `echo 'run your own sbot!' && electro main.js -- --title patchbay`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the patchbay@7.12.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ssb/.npm/_logs/2017-11-08T20_54_20_546Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ssb/.nvm/versions/node/v8.7.0/bin/node',
1 verbose cli   '/home/ssb/.nvm/versions/node/v8.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.5.1
3 info using node@v8.7.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle patchbay@7.12.2~predev: patchbay@7.12.2
6 info lifecycle patchbay@7.12.2~dev: patchbay@7.12.2
7 verbose lifecycle patchbay@7.12.2~dev: unsafe-perm in lifecycle true
8 verbose lifecycle patchbay@7.12.2~dev: PATH: /home/ssb/.nvm/versions/node/v8.7.0/lib/node_modules/npm/bin/node-gyp-bin:/home/ssb/code/patchbay/node_modules/.bin:/home/ssb/.nvm/versions/node/v8.7.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle patchbay@7.12.2~dev: CWD: /home/ssb/code/patchbay
10 silly lifecycle patchbay@7.12.2~dev: Args: [ '-c',
10 silly lifecycle   'echo \'run your own sbot!\' && electro main.js -- --title patchbay' ]
11 silly lifecycle patchbay@7.12.2~dev: Returned: code: 1  signal: null
12 info lifecycle patchbay@7.12.2~dev: Failed to exec dev script
13 verbose stack Error: patchbay@7.12.2 dev: `echo 'run your own sbot!' && electro main.js -- --title patchbay`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ssb/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/ssb/.nvm/versions/node/v8.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid patchbay@7.12.2
15 verbose cwd /home/ssb/code/patchbay
16 verbose Linux 4.13.0-1-amd64
17 verbose argv "/home/ssb/.nvm/versions/node/v8.7.0/bin/node" "/home/ssb/.nvm/versions/node/v8.7.0/bin/npm" "run" "dev"
18 verbose node v8.7.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error patchbay@7.12.2 dev: `echo 'run your own sbot!' && electro main.js -- --title patchbay`
22 error Exit status 1
23 error Failed at the patchbay@7.12.2 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by christianbundy** [comment]
Hey @ph1l! It *looks* like this may have been resolved in https://github.com/cryptix/electro/commit/480ab326ca3c0dde1122a8750fc005d8071800de, could you verify that the middle-click works again for you? My installation isn't crashing, but it's important that it's working right for you too!
