### ISSUE TITLE
npm start failed with error on loading leveldown.node

### ISSUE THREAD

**Issue by k4ml** [ssbc/patchbay#160]
This happened after I pulling the latest master:-

```
06:42:28 (master) ~/js/patchbay$ npm start

> patchbay@7.13.0 start /Users/kamal/js/patchbay
> electron index.js -- --title patchbay

STARTING electron
STARTING SBOT
Error: The module '/Users/kamal/js/patchbay/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/kamal/js/patchbay/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/kamal/js/patchbay/node_modules/leveldown/leveldown.js:4:46)
^C
```
I have try with `rm -rf node_modules` and running `npm install --build-from-source` but still not working.

```
06:42:42 (master) ~/js/patchbay$ type electron
electron is hashed (/usr/local/bin/electron)
```
```
06:45:51 (master) ~/js/patchbay$ cat /usr/local/bin/electron
#!/usr/bin/env node

var electron = require('./')

var proc = require('child_process')

var child = proc.spawn(electron, process.argv.slice(2), {stdio: 'inherit'})
child.on('close', function (code) {
  process.exit(code)
})
```

```
06:46:19 (master) ~/js/patchbay$ node -v
v6.11.4
```
```
06:46:41 (master) ~/js/patchbay$ npm -v
3.10.10
```

**Comment by k4ml** [comment]
Ughh, silly me. I missed the README.md mentioned about running `npm run rebuild`. It's work now.

**Comment by christianbundy** [comment]
Wow, I was having the same problem and tried running `npm rebuild` repeatedly but couldn't get it working. I reinstalled Node, NPM, and restarted my computer before noticing that `npm run rebuild` is a completely different command than `npm rebuild`.

Solution: `npm`**`run`**`rebuild`

I'm wondering whether `npm run electron-rebuild` might be more intuitive (with or without [the official module](https://github.com/electron/electron-rebuild)).

**Comment by cryptix** [comment]
>  before noticing that ...

assumptions: they all catch up to us one by one.... :wink:
