### ISSUE TITLE
Patch-hub is commented out?

### ISSUE THREAD

**Issue by arj03** [ssbc/patchbay#164]
Any reason for this, I find it really useful to see git-ssb message in the client. Commenting it in seems to work, so I'm just wondering why it was commented out?

**Comment by christianbundy** [comment]
I've tried re-adding it and it throws an error:

```
ReferenceError: opts is not defined
    at Object.render (/home/christianbundy/Source/patchbay/node_modules/patch-hub/message/html/render/git-update.js:25:8)
    at Object.render (/home/christianbundy/Source/patchbay/node_modules/depject/apply.js:18:30)
    at render (/home/christianbundy/Source/patchbay/app/page/public.js:67:33)
    at add (/home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:42:15)
    at /home/christianbundy/Source/patchbay/node_modules/pull-scroll/index.js:71:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-abortable/index.js:46:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-next/index.js:29:11
    at /home/christianbundy/Source/patchbay/node_modules/pull-stream/throughs/through.js:19:9
    at PacketStreamSubstream.weird.read (/home/christianbundy/Source/patchbay/node_modules/muxrpc/pull-weird.js:33:7)
```

Maybe something trivial? I'm not very familiar.

**Comment by cryptix** [comment]
patch-hub was an attempt to port the git-ssb features from parchfoo. It was put on ice though.

At this stage it needs a thorough re-write IIRC.

**Comment by christianbundy** [comment]
Thanks @cryptix. Should we close this issue and re-open if/when it gets rewritten?
