### ISSUE TITLE
empty screen `npm run start`

### ISSUE THREAD

**Issue by hardfire** [ssbc/patchbay#178]
I have a flourishing thing going on in patchwork world :D but when i run patchbay the UI is all empty.
![screen shot 2018-02-17 at 11 24 48](https://user-images.githubusercontent.com/513457/36338368-318b8702-13d5-11e8-80ac-b5d9c2a5fb12.png)

I am running patchbay on the current master branch. (on osx 10.12.6)
The console is full of TypeError {}

```
STARTING electron
STARTING SBOT
LOADING config
[fulltext] since 0
RELOAD 2 200166033
0 262152 65536 262152
262152 786448 131072 524296
786448 1835032 262144 1048584
1835032 3932192 524288 2097160
RELOADED 200166033
+++++++++++++++++++++++++++++++++++++++++++++++++++TypeError {}
TypeError {}
TypeError {}
LOADING config
TypeError {}
STARTING app
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
TypeError {}
```

what could be causing this issue?

**Comment by oren** [comment]
I am also getting empty screen. I don't even see the tabs.

```
npm start

> patchbay@7.13.1 start /home/oren/t/apps/patchbay
> electron index.js -- --title patchbay

STARTING electron
STARTING SBOT
LOADING config
Log level: notice
[fulltext] since 1482988095861.5515
+++++++++++++++++++++++++++++++++++++++++++++++++++LOADING config
STARTING app
TypeError: Cannot read property 'exclude' of undefined
    at Object.Filter (/home/oren/t/apps/patchbay/app/html/filter.js:37:32)
    at Object.filter (/home/oren/t/apps/patchbay/node_modules/depject/apply.js:15:30)
    at Array.publicPage (/home/oren/t/apps/patchbay/app/page/public.js:41:88)
    at Array.<anonymous> (/home/oren/t/apps/patchbay/node_modules/depject/apply.js:15:30)
    at /home/oren/t/apps/patchbay/node_modules/patchcore/router/sync/router.js:29:31
    at Object.nest (/home/oren/t/apps/patchbay/node_modules/patchcore/router/sync/router.js:20:12)
    at Object.router (/home/oren/t/apps/patchbay/node_modules/depject/apply.js:15:30)
    at Object.goTo (/home/oren/t/apps/patchbay/app/sync/goTo.js:35:34)
    at Object.goTo (/home/oren/t/apps/patchbay/node_modules/depject/apply.js:15:30)
    at initialTabs.forEach.p (/home/oren/t/apps/patchbay/app/html/tabs.js:64:43)
CONNECT { host: 'pub.doge.haus',
  port: 8008,
  key: '@7nTbqZVRYRo7FokY8BBYGpXvvveRPb4u+G1vunRmNn4=.ed25519',
  source: 'stored',
  announcers: 160,
  duration: 
   { mean: 47505.45714285714,
     stdev: 269138.1653677258,
     count: 70,
     sum: 3325382,
     sqsum: 5228448436110 },
  stateChange: 1518299426776,
  client: true,
  ping: 
   { rtt: { mean: 737, stdev: 0, count: 1, sum: 737, sqsum: 543169 },
     skew: { mean: -200.5, stdev: 0, count: 1, sum: -200.5, sqsum: 40200.25 } },
  failure: 25,
  error: 'Error: connect ECONNREFUSED 104.236.93.59:8008\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)' }
CONNECT { host: 'cryptoscope.co',
  port: 8008,
  key: '@G20wv2IZkB7BA/LKe7WMuByop3++J0u9+Y32OoEVOj8=.ed25519',
  source: 'stored',
  announcers: 2,
  duration: 
   { mean: 22575.484848484848,
     stdev: 108951.87445899477,
     count: 33,
     sum: 744991,
     sqsum: 408545394321 },
  stateChange: 1518299432758,
  failure: 27,
  client: true,
  ping: 
   { rtt: { mean: 731.5, stdev: 206.5, count: 2, sum: 1463, sqsum: 1155469 },
     skew: 
      { mean: -440.75,
        stdev: 170.25,
        count: 2,
        sum: -881.5,
        sqsum: 446491.25 } },
  error: 'Error: connect ECONNREFUSED 139.59.136.165:8008\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)' }
CONNECT { host: '96.126.105.156',
  port: 8008,
  key: '@sofM1yiz4z/mHlNB6qsyUQ02UDnbr+pjrIE3/H/z2TA=.ed25519',
  source: 'stored',
  announcers: 2,
  duration: null }
CONNECT { host: 'sbot.ktorn.com',
  port: 8008,
  key: '@BzMp3eRNjPUonwRd/0loT3KaRKIMFx7ZOZQE1F+XDug=.ed25519',
  source: 'stored',
  announcers: 23,
  duration: 
   { mean: 686351.2659574468,
     stdev: 3885383.034627803,
     count: 94,
     sum: 64517019,
     sqsum: 1463324262289165 },
  stateChange: 1518299444005,
  client: true,
  ping: 
   { rtt: 
      { mean: 487.75,
        stdev: 674.2682607834955,
        count: 4,
        sum: 1951,
        sqsum: 2770151 },
     skew: 
      { mean: -2610.125,
        stdev: 352.71932449895627,
        count: 4,
        sum: -10440.5,
        sqsum: 27748653.75 } },
  failure: 24,
  error: 'Error: challenge not accepted\n    at abort (/tmp/.mount_Patchwpsgkxn/app/resources/app.asar/node_modules/secret-handshake/protocol.js:36:45)\n    at Object.cb (/tmp/.mount_Patchwpsgkxn/app/resources/app.asar/node_modules/secret-handshake/protocol.js:42:24)\n    at drain (/tmp/.mount_Patchwpsgkxn/app/resources/app.asar/node_modules/pull-reader/index.js:42:23)\n    at /tmp/.mount_Patchwpsgkxn/app/resources/app.asar/node_modules/pull-reader/index.js:59:18\n    at /tmp/.mount_Patchwpsgkxn/app/resources/app.asar/node_modules/pull-reader/index.js:20:7\n    at /tmp/.mount_Patchwpsgkxn/app/resources/app.asar/node_modules/pull-stream/throughs/through.js:19:9\n    at drain (/tmp/.mount_Patchwpsgkxn/app/resources/app.asar/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/tmp/.mount_Patchwpsgkxn/app/resources/app.asar/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:120:20)\n    at Socket.emit (events.js:210:7)' }
CONNECT { host: 'mindeco.de',
  port: 110,
  key: '@Uki1+Hds2kkx4rOWl202SPfcsgsdaLHJ/Y6OfPnK1xk=.ed25519',
  source: 'stored',
  announcers: 15,
  duration: 
   { mean: 543281.8313253012,
   stdev: 4747166.645046814,
     count: 83,
     sum: 45092392,
     sqsum: 1894951943239736 },
  stateChange: 1518299450830,
  failure: 78,
  client: true,
  ping: 
   { rtt: { mean: 1044.5, stdev: 557.5, count: 2, sum: 2089, sqsum: 2803573 },
     skew: 
      { mean: -232.75,
        stdev: 214.25,
        count: 2,
        sum: -465.5,
        sqsum: 200151.25 } },
  error: 'Error: getaddrinfo ENOTFOUND mindeco.de mindeco.de:110\n    at errnoException (dns.js:50:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)' }
^C
```

Other useful information about my OS:
lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

uname -a

```
Linux oren 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hardfire** [comment]
@oren i just tested on ubuntu and i have the same issue as well. Not tabs on linux.

![image](https://user-images.githubusercontent.com/513457/36348200-717b10ea-1492-11e8-8abf-a6283f1233cb.png)

**Comment by mmckegg** [comment]
Just got this too. With the following error:

```
base.html:19 TypeError: Cannot read property 'exclude' of undefined
    at Object.Filter (/Users/matt/Code/patchbay/app/html/filter.js:37:32)
    at Object.filter (/Users/matt/Code/patchbay/node_modules/depject/apply.js:15:30)
    at Array.publicPage (/Users/matt/Code/patchbay/app/page/public.js:41:88)
    at Array.<anonymous> (/Users/matt/Code/patchbay/node_modules/depject/apply.js:15:30)
    at /Users/matt/Code/patchbay/node_modules/patchcore/router/sync/router.js:29:31
    at Object.nest (/Users/matt/Code/patchbay/node_modules/patchcore/router/sync/router.js:20:12)
    at Object.router (/Users/matt/Code/patchbay/node_modules/depject/apply.js:15:30)
    at Object.goTo (/Users/matt/Code/patchbay/app/sync/goTo.js:35:34)
    at Object.goTo (/Users/matt/Code/patchbay/node_modules/depject/apply.js:15:30)
    at initialTabs.forEach.p (/Users/matt/Code/patchbay/app/html/tabs.js:64:43)
```

I'm gonna fix it!! BRB!

**Comment by hardfire** [comment]
awesome! thanks @mmckegg

**Comment by hardfire** [comment]
wohoo!! nice!
![image](https://user-images.githubusercontent.com/513457/36462894-5c9942b0-16ee-11e8-8022-feaf1f6fb638.png)

**Comment by oren** [comment]
Just tested @mmckegg's branch. works for me as well. Thank you.

**Comment by Happy0** [comment]
Come and review some books and play some chess, @hardfire , @oren :p 

(They're in the menu at the top right.)
