### ISSUE TITLE
TypeError: Failed to execute 'scroll' on 'Element'

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay#222]
I was trying to debug something and ran `Ctrl + Shift + K`, which triggered an error.

```
TypeError: Failed to execute 'scroll' on 'Element': parameter 1 ('options') is not an object.
    at genericShortcuts (/home/christianbundy/Source/patchbay/app/sync/catch-keyboard-shortcut.js:65:33)
    at root.addEventListener (/home/christianbundy/Source/patchbay/app/sync/catch-keyboard-shortcut.js:24:11)
```

**Comment by christianbundy** [comment]
Potentially related, I'm now getting this when I close out of all Patchbay tabs:

```
TypeError: Cannot read property 'scroll' of undefined
    at genericShortcuts (/opt/patchbay-git/app/sync/catch-keyboard-shortcut.js:47:36)
    at root.addEventListener (/opt/patchbay-git/app/sync/catch-keyboard-shortcut.js:24:11)
```

**Comment by cryptix** [comment]
I also got the `TypeError: Cannot read property 'scroll' of undefined` after loading - no tabs showed up, just this error.

pressing ctrl+r two times made it work somehow.
