### ISSUE TITLE
Error: Threshold number of shares must be an integer between 2 and 2^bits-1 (255), inclusive.

### ISSUE THREAD

**Issue by christianbundy** [ssbc/patchbay#225]
Tried to test whether https://github.com/ssbc/scuttle-invite/pull/8 worked by creating a dark crystal with @mixmix and @cryptix, but when setting the quorum to 1 it broke and crashed Patchbay. Maybe just something to fix in the UI?

```
Error: Threshold number of shares must be an integer between 2 and 2^bits-1 (255), inclusive.
    at Object.share (/home/christianbundy/Source/patchbay/node_modules/secrets.js-grempe/secrets.js:786:23)
    at /home/christianbundy/Source/patchbay/node_modules/scuttle-dark-crystal/share/async/share.js:41:28
    at server (/home/christianbundy/Source/patchbay/node_modules/scuttle-inject/index.js:34:32)
    at watch (/home/christianbundy/Source/patchbay/node_modules/mutant/once-true.js:8:7)
    at watch (/home/christianbundy/Source/patchbay/node_modules/mutant/watch.js:7:5)
    at onceTrue (/home/christianbundy/Source/patchbay/node_modules/mutant/once-true.js:4:17)
    at Object.share (/home/christianbundy/Source/patchbay/node_modules/scuttle-inject/index.js:32:9)
    at performRitual (/home/christianbundy/Source/patchbay/node_modules/patchbay-dark-crystal/views/new.js:98:25)
    at HTMLButtonElement.ev-click (/home/christianbundy/Source/patchbay/node_modules/patchbay-dark-crystal/views/new.js:75:52)
TypeError: release is not a function
    at Immediate.doRelease [as _onImmediate] (/home/christianbundy/Source/patchbay/node_modules/mutant/once-true.js:15:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
``

**Comment by christianbundy** [comment]
Should this be moved to https://github.com/blockades/patchbay-dark-crystal?
