### ISSUE TITLE
Cannot read property 'minDate' of undefined

### ISSUE THREAD

**Issue by cryptix** [ssbc/patchbay#242]
tried to update the date on a gathering but got this:

```
TypeError: Cannot read property 'minDate' of undefined
    at isEnabled (/home/cryptix/ssb/patchbay/node_modules/flatpickr/dist/flatpickr.js:921:19)
    at /home/cryptix/ssb/patchbay/node_modules/flatpickr/dist/flatpickr.js:1367:32
    at Array.filter (<anonymous>)
    at setSelectedDate (/home/cryptix/ssb/patchbay/node_modules/flatpickr/dist/flatpickr.js:1366:43)
    at Flatpickr.setDate (/home/cryptix/ssb/patchbay/node_modules/flatpickr/dist/flatpickr.js:1378:3)
    at Array.startDateTime (/home/cryptix/ssb/patchbay/node_modules/patch-gatherings/gathering/html/startDateTime.js:43:42)
    at Observable.observable.set (/home/cryptix/ssb/patchbay/node_modules/mutant/value.js:12:25)
    at /home/cryptix/ssb/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/cryptix/ssb/patchbay/node_modules/pull-stream/throughs/map.js:19:9
    at /home/cryptix/ssb/patchbay/node_modules/pull-stream/throughs/map.js:19:9
    at /home/cryptix/ssb/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at /home/cryptix/ssb/patchbay/node_modules/pull-stream/throughs/filter.js:17:11
    at callback (/home/cryptix/ssb/patchbay/node_modules/pull-pushable/index.js:84:5)
    at Function.push (/home/cryptix/ssb/patchbay/node_modules/pull-pushable/index.js:44:7)
    at notify (/home/cryptix/ssb/patchbay/node_modules/pull-notify/index.js:10:20)
    at /home/cryptix/ssb/patchbay/node_modules/pull-stream/sinks/drain.js:24:37
```

**Comment by christianbundy** [comment]
I think this might be the same as #125.

**Comment by christianbundy** [comment]
Thanks for the :+1:, I'll close this as a duplicate -- please reopen if I've misunderstood!
