### ISSUE TITLE
get error when opening polls tab

### ISSUE THREAD

**Issue by Musickiller** [ssbc/patchbay#310]
patchbay bug: when I open polls, I see this message:

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of closesAt.toTimeString(...).match
    at PollCard (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\patchbay-poll\views\com\poll-card.js:15:53)
    at render (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\patchbay-poll\views\index.js:35:16)
    at updateItem (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\mutant\map.js:227:24)
    at update (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\mutant\map.js:106:11)
    at Object.updateAndBroadcast (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\mutant\lib\lazy-watcher.js:54:18)
    at Array.onUpdate (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\mutant\lib\lazy-watcher.js:48:13)
    at broadcast (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\mutant\lib\lazy-watcher.js:111:27)
    at Object.broadcast (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\mutant\lib\lazy-watcher.js:24:9)
    at Function.Array.observable.push (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\mutant\array.js:50:12)
    at updateBottomDefault (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\patchbay-poll\node_modules\mutant-scroll\index.js:32:11)
    at addBottom (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\patchbay-poll\node_modules\mutant-scroll\index.js:87:7)
    at Scroller.pull.drain.e (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\patchbay-poll\node_modules\mutant-scroll\index.js:138:11)
    at C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\pull-stream\sinks\drain.js:24:37
    at C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\pull-next\index.js:29:11
    at C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\pull-stream\throughs\through.js:19:9
    at PacketStreamSubstream.weird.read (C:\Users\User\AppData\Local\Programs\patchbay\resources\app.asar\node_modules\muxrpc\pull-weird.js:33:7)
```

...and it also does not sync.

**Comment by mixmix** [comment]
I think this is resolved
