### ISSUE TITLE
Broken Feed?

### ISSUE THREAD

**Issue by KGibb8** [ssbc/patchbay#313]
On starting Patchbay, I get the following error...

@mixmix Is this more relevant to flume?

```
Error: view stream error
    at /shared/Projects/patchbay/node_modules/flumedb/index.js:139:35
    at /shared/Projects/patchbay/node_modules/pull-stream/sinks/drain.js:20:24
    at /shared/Projects/patchbay/node_modules/pull-stream/throughs/async-map.js:28:19
    at /shared/Projects/patchbay/node_modules/pull-cursor/skip.js:12:26
    at /shared/Projects/patchbay/node_modules/pull-cursor/cursor.js:28:28
    at /shared/Projects/patchbay/node_modules/flumelog-offset/inject.js:42:22
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at Object.read (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:49:14)
  Error: past end:649935989-2097188320 < 650704372
    at Object.read (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:95:11
    at get (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:92:9)
    at /shared/Projects/patchbay/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at Array.<anonymous> (/shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:95:11)
    at /shared/Projects/patchbay/node_modules/aligned-block-file/blocks.js:39:16
    at /shared/Projects/patchbay/node_modules/aligned-block-file/file.js:46:13
```

**Comment by cryptix** [comment]
hmmm... this smells like a corrupted offset log. Do you also get this when you start ssb-server stand-alone?

**Comment by christianbundy** [comment]
Yep, that looks like corruption to me.

@KGibb8 do you have any posts in your log that haven't already been published to the network?

**Comment by cryptix** [comment]
I just got this during testing the new invites and now get it on each startup of ssb-server 

```
[gossip] warning: this can happen if the database closes [Arguments] {:42.9%, ebt:5.4%)
  '0':
   Error: when trying to retrive:type,pub,1549573034693.001at since:223387490
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/flumeview-level/index.js:139:28
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/flumedb/index.js:70:17
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/flumelog-offset/inject.js:75:17
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:48:11
       at Object.read (/Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:14)
     Error: past end:32436663-2050384395 < 223388015
       at Object.read (/Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:17)
       at next (/Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:47:16)
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:43:11
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:95:11
       at get (/Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
       at Object.readUInt32BE (/Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:92:9)
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:41:16
       at Array.<anonymous> (/Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:95:11)
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:39:16
       at /Users/cryptix/ssb/scuttle-shell/node_modules/ssb-server/node_modules/aligned-block-file/file.js:46:13 }
```

also an /error tab opens in patchbay:

```
Error: when trying to retrive:typ,post,1549573035985.002at since:357853982
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/flumeview-level/index.js:139:28
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumedb/index.js:70:17
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/inject.js:75:17
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:48:11
    at Object.read (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:14)
  Error: past end:32913462-1667805526 < 357854548
    at Object.read (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:49:17)
    at next (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:47:16)
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:43:11
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:95:11
    at get (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:92:9)
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/flumelog-offset/frame/recoverable.js:41:16
    at /Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:95:11
    at get (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:29:7)
    at Object.readUInt32BE (/Applications/patchbay.app/Contents/Resources/app.asar/node_modules/ssb-server/node_modules/aligned-block-file/blocks.js:92:9)
```
