### ISSUE TITLE
weird error trying to run patchbay

### ISSUE THREAD

**Issue by dominictarr** [ssbc/patchbay#335]
when patchbay is missing something it doesn't error is a very helpful way

![2019-05-16-141738_877x457_scrot](https://user-images.githubusercontent.com/259374/57853222-75dacb00-77e5-11e9-84da-7524f79b660f.png)

copypastable:
```
TypeError: Cannot read property 'message' of undefined
    at Object.addError (/home/dominic/c/patchbay/app/page/errors.js:21:25)
    at item (/home/dominic/c/patchbay/node_modules/hyperscript/index.js:73:26)
    at h (/home/dominic/c/patchbay/node_modules/hyperscript/index.js:116:7)
    at HTMLDivElement.d.add (/home/dominic/c/patchbay/node_modules/hypertabs/index.js:39:16)
    at api.router.async.router (/home/dominic/c/patchbay/app/sync/go-to.js:59:14)
    at Router (/home/dominic/c/patchbay/router/async/router.js:34:16)
    at api.router.async.normalise (/home/dominic/c/patchbay/router/async/router.js:21:7)
    at Object.normalise (/home/dominic/c/patchbay/router/async/normalise.js:17:7)
    at Object.normalise (/home/dominic/c/patchbay/node_modules/depject/apply.js:18:30)
    at Object.nest (/home/dominic/c/patchbay/router/async/router.js:18:22)
    at Object.router (/home/dominic/c/patchbay/node_modules/depject/apply.js:18:30)
    at api.router.async.normalise (/home/dominic/c/patchbay/app/sync/go-to.js:53:24)
    at Object.normalise (/home/dominic/c/patchbay/router/async/normalise.js:56:32)
    at Object.normalise (/home/dominic/c/patchbay/node_modules/depject/apply.js:18:30)
    at Object.goTo (/home/dominic/c/patchbay/app/sync/go-to.js:34:22)
    at Object.goTo (/home/dominic/c/patchbay/node_modules/depject/apply.js:18:30)`
```

I have all the right plugins, so not sure what is wrong here. running in `npm run dev` mode.

**Comment by mixmix** [comment]
npm run dev doesn't work any more.

It could be made to work. Lemme give it ten minutes, otherwise I'll go ahead and delete it.

**Comment by mixmix** [comment]
I've got this working again - it's now under `npm run lite`

**Comment by mixmix** [comment]
make sure you pull that latest `master` there's been some quite big changes

**Comment by dominictarr** [comment]
@mixmix it works again, thanks
