### ISSUE TITLE
/books doesn't show any books

### ISSUE THREAD

**Issue by zweutisiouz** [ssbc/patchbay#367]
I tried to open /books in patchbay 8.1.0 and it opens a /errors tab:
I use Linux Mint Cinnamon 19.3 with the AppImage.
```
Cannot read property 'shelves' of undefined
TypeError: Cannot read property 'shelves' of undefined
    at pull.drain (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/patchbay-book/plugs/app/page/books.js:139:46)
    at /tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at drain (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/pull-paramap/index.js:19:11)
    at /tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/pull-paramap/index.js:45:13
    at getter (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/scuttle-book/pull/books.js:28:11)
    at applyAmends (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/scuttle-book/async/get.js:44:9)
    at pull.drain (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/scuttle-book/async/get.js:131:9)
    at /tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/pull-stream/sinks/drain.js:20:24
    at PacketStreamSubstream.weird.read (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/packet-stream/index.js:200:12)
    at PacketStream.write (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/packet-stream/index.js:135:41)
    at /tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/muxrpc/pull-weird.js:56:15
    at /tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at /tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/tmp/.mount_patchbdQ21IK/resources/app.asar/node_modules/pull-reader/index.js:39:14)
```
![Bildschirmfoto vom 2020-02-16 18-49-29](https://user-images.githubusercontent.com/46935858/74609733-1d768800-50ed-11ea-8ad9-c2f55bffeab4.png)

**Comment by arj03** [comment]
I think the problem might be that you are not connected to any users who has written book reviews ;-) Does it make a difference if you connect to @6CAxOI3f+LUOVrbAl0IemqiS7ATpQvr9Mdw9LC4+Uv0=.ed25519?

**Comment by zweutisiouz** [comment]
Ok, i have followed @6CAx... 
And I tried to open Patchbay and nothing has changed. 
The Terminal-Log shows:
```
user@system:/data/user/misc/AppImages$ ./patchbay-Linux-8.1.0-x86_64.AppImage 
# AHOY: (main)     starting UI
friends hops: 3
# AHOY: (ui)       SENDING  >> ahoy:step
# AHOY: (main)     clearing UI
# ---------------
# AHOY: (main)     starting Server
# AHOY: (main)     starting UI
ssb-friends: stream legacy api used
STARTING Patchbay UI
Error replicating with @GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/stream.js:116:17)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/index.js:46:15
    at remoteCall (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:25:18)
    at replicate (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-replicate/legacy.js:351:7)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-ebt/index.js:129:15
Error replicating with @5XaVcAJ5DklwuuIkjGz4lwm2rOnMHHovhNg7BFFnyJ8=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/stream.js:116:17)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/index.js:46:15
    at remoteCall (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:25:18)
    at replicate (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-replicate/legacy.js:351:7)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-ebt/index.js:129:15
Error replicating with @WndnBREUvtFVF14XYEq01icpt91753bA+nVycEJIAX4=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/stream.js:116:17)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/index.js:46:15
    at remoteCall (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:25:18)
    at replicate (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-replicate/legacy.js:351:7)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-ebt/index.js:129:15
{ message:
   'Cannot read property \'@CBbEB9GTG1RsZU4MKYFERAp3pINa9LblFq03WeieP0w=.ed25519\' of null',
  name: 'TypeError',
  stack:
   'TypeError: Cannot read property \'@CBbEB9GTG1RsZU4MKYFERAp3pINa9LblFq03WeieP0w=.ed25519\' of null\n    at Object.peerStatus (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-ebt/index.js:179:22)\n    at Object.<anonymous> (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/secret-stack/util.js:80:17)\n    at Object.<anonymous> (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/hoox/index.js:3:17)\n    at Object.hooked (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/hoox/index.js:10:15)\n    at Object.localCall (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/local-api.js:23:40)\n    at Object.<anonymous> (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/local-api.js:37:22)\n    at Object.request (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/stream.js:48:17)\n    at PacketStream._onrequest (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/packet-stream/index.js:161:17)\n    at PacketStream.write (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/packet-stream/index.js:134:41)\n    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15' }
TypeError: Cannot read property 'shelves' of undefined
    at pull.drain (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/patchbay-book/plugs/app/page/books.js:139:46)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at drain (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/pull-paramap/index.js:19:11)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/pull-paramap/index.js:45:13
    at getter (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/scuttle-book/pull/books.js:28:11)
    at applyAmends (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/scuttle-book/async/get.js:44:9)
    at pull.drain (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/scuttle-book/async/get.js:131:9)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/pull-stream/sinks/drain.js:20:24
    at PacketStreamSubstream.weird.read (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/packet-stream/index.js:200:12)
    at PacketStream.write (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/packet-stream/index.js:135:41)
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/muxrpc/pull-weird.js:56:15
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/pull-reader/index.js:39:14)
# AHOY: (main)     quitting
```
After that i closed Patchbay and tried again but this time i pressed "Initial Sync" in AHOY. And this time everything works fine, but there are still no books visible.
```
user@system:/data/user/misc/AppImages$ ./patchbay-Linux-8.1.0-x86_64.AppImage 
# AHOY: (main)     starting UI
friends hops: 3
# AHOY: (ui)       SENDING  >> ahoy:step
# AHOY: (main)     clearing UI
# ---------------
# AHOY: (main)     starting Server
# AHOY: (main)     starting UI
ssb-friends: stream legacy api used
# AHOY: (ui)       SENDING  >> ahoy:step
# AHOY: (main)     clearing Server
# AHOY: (server)   RECEIVED << server-close
# AHOY: (main)     RECEIVED << server-closed
# AHOY: (main)     clearing UI
# ---------------
# AHOY: (main)     starting Server
fallback to close
# AHOY: (main)     starting UI
ssb-friends: stream legacy api used
STARTING Patchbay UI
Error replicating with @GPz52umhSy9c4Qu7jBLd9mDOysvxyy3TcjzUzsaZHVA=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/stream.js:116:17)
    at /tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/index.js:46:15
    at remoteCall (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:25:18)
    at replicate (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-replicate/legacy.js:351:7)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-ebt/index.js:129:15
Error replicating with @1nXNP4vDRn2Y7LsPA9/VTRnFOOKjsjf2ioeA2wW50KQ=.ed25519:
   Error: parent stream is closing
    at PacketStream.stream (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/packet-stream/index.js:46:28)
    at Object.ws.remoteCall (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/stream.js:116:17)
    at /tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/index.js:46:15
    at remoteCall (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:40:19)
    at EventEmitter.obj.(anonymous function) [as createHistoryStream] (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-server/node_modules/muxrpc/api.js:25:18)
    at replicate (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-replicate/legacy.js:291:13)
    at EventEmitter.fallback (/tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-replicate/legacy.js:351:7)
    at Object.onceWrapper (events.js:273:13)
    at EventEmitter.emit (events.js:182:13)
    at /tmp/.mount_patchbxI8Amq/resources/app.asar/node_modules/ssb-ebt/index.js:129:15
# AHOY: (main)     quitting
```
I tried restarting it a few times and it has to sync about 200 MB every time i press the initial sync button. And it shows the error message every time i start patchbay normally.
My theory is that Patchbay can't save the synced data somehow.

**Comment by arj03** [comment]
It seems as if you for some reason have a book that is malformed. Can you uncomment this line an see what the book looks like?

https://github.com/ssbc/patchbay-book/blob/master/plugs/app/page/books.js#L123

Should be in /tmp/.mount_patchbf5BSjC/resources/app.asar/node_modules/scuttle-book/pull/books.js on your machine.

**Comment by aadilayub** [comment]
I'm experiencing this issue as well. Judging from what I saw in the #books tag on patchwork, I'm pretty sure I'm connected to some users who have written book reviews.

**Comment by aadilayub** [comment]
@arj03 I tried editing `books.js` like you suggested in your earlier comment, but couldn't find it in my filesystem (it looks like `app.asar` is not a directory)

![image](https://user-images.githubusercontent.com/31581044/82573983-e908e100-9b9f-11ea-84c9-99375e2299bf.png)

Any suggestions?

**Comment by arj03** [comment]
You need to run it from source @aadilayub
