### ISSUE TITLE
Mysterious TypeError

### ISSUE THREAD

**Issue by clehner** [ssbc/patchbay#37]
This shows up sometimes on load in the errors tab or console:

```
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:249:9)
    at Function.Buffer.from (buffer.js:115:10)
    at new Buffer (buffer.js:94:17)
    at EventEmitter.<anonymous> (file:///usr/local/src/patchbay/node_modules/electro/index.html?argv%3Delectro%26argv%3D.%26stdin%3D%26stderr%3D%26stdout%3D:24:23)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

**Comment by evbogue** [comment]
This hasn't been seen or heard from in awhile.
