### ISSUE TITLE
sbot crash on installation attempt

### ISSUE THREAD

**Issue by noffle** [ssbc/patchbay#88]
I'm having trouble installing patchbay. Following the instructions, I install `scuttlebot@latest`, then..

```
[sww@figure8 patchbay]$ sbot plugins.install ssb-links
Installing "ssb-links"...

> leveldown@1.6.0 install /tmp/node_modules/ssb-links/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.1.0
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.6.0-node-v51-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/sww/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v51-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/sww/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v51-linux-x64.tar.gz
prebuild-install info unpack resolved to /tmp/node_modules/ssb-links/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /tmp/node_modules/ssb-links/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Prebuild successfully installed!
- abbrev@1.0.9 node_modules/ssb-links/node_modules/abbrev
- after@0.8.2 node_modules/ssb-links/node_modules/after
- ansi@0.3.1 node_modules/ssb-links/node_modules/ansi
- ansi-styles@2.2.1 node_modules/ssb-links/node_modules/ansi-styles
- asn1@0.2.3 node_modules/ssb-links/node_modules/asn1
- assert-plus@0.2.0 node_modules/ssb-links/node_modules/assert-plus
- asynckit@0.4.0 node_modules/ssb-links/node_modules/asynckit
- aws-sign2@0.6.0 node_modules/ssb-links/node_modules/aws-sign2
- aws4@1.5.0 node_modules/ssb-links/node_modules/aws4
- balanced-match@0.4.2 node_modules/ssb-links/node_modules/balanced-match
- block-stream@0.0.9 node_modules/ssb-links/node_modules/block-stream
- caseless@0.11.0 node_modules/ssb-links/node_modules/caseless
- supports-color@2.0.0 node_modules/ssb-links/node_modules/chalk/node_modules/supports-color
- concat-map@0.0.1 node_modules/ssb-links/node_modules/concat-map
- brace-expansion@1.1.6 node_modules/ssb-links/node_modules/brace-expansion
- assert-plus@1.0.0 node_modules/ssb-links/node_modules/dashdash/node_modules/assert-plus
- dashdash@1.14.1 node_modules/ssb-links/node_modules/dashdash
- delayed-stream@1.0.0 node_modules/ssb-links/node_modules/delayed-stream
- combined-stream@1.0.5 node_modules/ssb-links/node_modules/combined-stream
- duplexer2@0.0.2 node_modules/ssb-links/node_modules/duplexer2
- es6-symbol@3.1.0 node_modules/ssb-links/node_modules/es6-symbol
- es6-iterator@2.0.0 node_modules/ssb-links/node_modules/es6-iterator
- es5-ext@0.10.12 node_modules/ssb-links/node_modules/es5-ext
- d@0.1.1 node_modules/ssb-links/node_modules/d
- escape-string-regexp@1.0.5 node_modules/ssb-links/node_modules/escape-string-regexp
- extend@3.0.0 node_modules/ssb-links/node_modules/extend
- extsprintf@1.0.2 node_modules/ssb-links/node_modules/extsprintf
- forever-agent@0.6.1 node_modules/ssb-links/node_modules/forever-agent
- fs.realpath@1.0.0 node_modules/ssb-links/node_modules/fs.realpath
- generate-function@2.0.0 node_modules/ssb-links/node_modules/generate-function
- assert-plus@1.0.0 node_modules/ssb-links/node_modules/getpass/node_modules/assert-plus
- getpass@0.1.6 node_modules/ssb-links/node_modules/getpass
- graceful-fs@4.1.11 node_modules/ssb-links/node_modules/graceful-fs
- graceful-readlink@1.0.1 node_modules/ssb-links/node_modules/graceful-readlink
- commander@2.9.0 node_modules/ssb-links/node_modules/commander
- has-ansi@2.0.0 node_modules/ssb-links/node_modules/has-ansi
- chalk@1.1.3 node_modules/ssb-links/node_modules/chalk
- hoek@2.16.3 node_modules/ssb-links/node_modules/hoek
- boom@2.10.1 node_modules/ssb-links/node_modules/boom
- cryptiles@2.0.5 node_modules/ssb-links/node_modules/cryptiles
- inflight@1.0.6 node_modules/ssb-links/node_modules/inflight
- is-property@1.0.2 node_modules/ssb-links/node_modules/is-property
- generate-object-property@1.2.0 node_modules/ssb-links/node_modules/generate-object-property
- is-typedarray@1.0.0 node_modules/ssb-links/node_modules/is-typedarray
- isexe@1.1.2 node_modules/ssb-links/node_modules/isexe
- isstream@0.1.2 node_modules/ssb-links/node_modules/isstream
- jsbn@0.1.0 node_modules/ssb-links/node_modules/jsbn
- ecc-jsbn@0.1.1 node_modules/ssb-links/node_modules/ecc-jsbn
- jodid25519@1.0.2 node_modules/ssb-links/node_modules/jodid25519
- json-schema@0.2.3 node_modules/ssb-links/node_modules/json-schema
- json-stringify-safe@5.0.1 node_modules/ssb-links/node_modules/json-stringify-safe
- jsonpointer@4.0.1 node_modules/ssb-links/node_modules/jsonpointer
- is-my-json-valid@2.15.0 node_modules/ssb-links/node_modules/is-my-json-valid
- lodash@4.17.4 node_modules/ssb-links/node_modules/lodash
- async@2.1.4 node_modules/ssb-links/node_modules/async
- lodash.pad@4.5.1 node_modules/ssb-links/node_modules/lodash.pad
- lodash.padend@4.6.1 node_modules/ssb-links/node_modules/lodash.padend
- lodash.padstart@4.6.1 node_modules/ssb-links/node_modules/lodash.padstart
- mime-db@1.26.0 node_modules/ssb-links/node_modules/mime-db
- mime-types@2.1.14 node_modules/ssb-links/node_modules/mime-types
- form-data@2.1.2 node_modules/ssb-links/node_modules/form-data
- minimatch@3.0.3 node_modules/ssb-links/node_modules/minimatch
- ms@0.7.2 node_modules/ssb-links/node_modules/ms
- debug@2.6.0 node_modules/ssb-links/node_modules/debug
- array-index@1.0.0 node_modules/ssb-links/node_modules/array-index
- gauge@1.2.7 node_modules/ssb-links/node_modules/node-ninja/node_modules/gauge
- npmlog@2.0.4 node_modules/ssb-links/node_modules/node-ninja/node_modules/npmlog
- nopt@3.0.6 node_modules/ssb-links/node_modules/nopt
- oauth-sign@0.8.2 node_modules/ssb-links/node_modules/oauth-sign
- os-tmpdir@1.0.2 node_modules/ssb-links/node_modules/os-tmpdir
- osenv@0.1.4 node_modules/ssb-links/node_modules/osenv
- path-array@1.0.1 node_modules/ssb-links/node_modules/path-array
- path-is-absolute@1.0.1 node_modules/ssb-links/node_modules/path-is-absolute
- glob@7.1.1 node_modules/ssb-links/node_modules/glob
- pinkie@2.0.4 node_modules/ssb-links/node_modules/pinkie
- pinkie-promise@2.0.1 node_modules/ssb-links/node_modules/pinkie-promise
- har-validator@2.0.6 node_modules/ssb-links/node_modules/har-validator
- punycode@1.4.1 node_modules/ssb-links/node_modules/punycode
- qs@6.3.0 node_modules/ssb-links/node_modules/qs
- rimraf@2.5.4 node_modules/ssb-links/node_modules/rimraf
- fstream@1.0.10 node_modules/ssb-links/node_modules/fstream
- simple-mime@0.1.0 node_modules/ssb-links/node_modules/simple-mime
- sntp@1.0.9 node_modules/ssb-links/node_modules/sntp
- hawk@3.1.3 node_modules/ssb-links/node_modules/hawk
- assert-plus@1.0.0 node_modules/ssb-links/node_modules/sshpk/node_modules/assert-plus
- stringstream@0.0.5 node_modules/ssb-links/node_modules/stringstream
- tar@2.2.1 node_modules/ssb-links/node_modules/tar
- readable-stream@1.0.34 node_modules/ssb-links/node_modules/through2/node_modules/readable-stream
- through2@0.6.5 node_modules/ssb-links/node_modules/through2
- hyperquest@1.2.0 node_modules/ssb-links/node_modules/hyperquest
- jsonist@1.3.0 node_modules/ssb-links/node_modules/jsonist
- ghutils@3.2.1 node_modules/ssb-links/node_modules/ghutils
- ghrepos@2.0.0 node_modules/ssb-links/node_modules/ghrepos
- tough-cookie@2.3.2 node_modules/ssb-links/node_modules/tough-cookie
- tweetnacl@0.14.5 node_modules/ssb-links/node_modules/tweetnacl
- bcrypt-pbkdf@1.0.1 node_modules/ssb-links/node_modules/bcrypt-pbkdf
- sshpk@1.10.2 node_modules/ssb-links/node_modules/sshpk
- url-template@2.0.8 node_modules/ssb-links/node_modules/url-template
- ghreleases@1.0.5 node_modules/ssb-links/node_modules/ghreleases
- util-extend@1.0.3 node_modules/ssb-links/node_modules/util-extend
- execspawn@1.0.1 node_modules/ssb-links/node_modules/execspawn
- uuid@3.0.1 node_modules/ssb-links/node_modules/uuid
- verror@1.3.6 node_modules/ssb-links/node_modules/verror
- jsprim@1.3.1 node_modules/ssb-links/node_modules/jsprim
- http-signature@1.1.1 node_modules/ssb-links/node_modules/http-signature
- request@2.79.0 node_modules/ssb-links/node_modules/request
- which@1.2.12 node_modules/ssb-links/node_modules/which
- node-gyp@3.5.0 node_modules/ssb-links/node_modules/node-gyp
- node-ninja@1.0.2 node_modules/ssb-links/node_modules/node-ninja
- prebuild@5.1.2 node_modules/ssb-links/node_modules/prebuild
dummy@1.0.0 /tmp
└─┬ ssb-links@2.0.0 
  └─┬ streamview-links@2.1.1
    └─┬ level@1.6.0 
      └─┬ leveldown@1.6.0 
        ├── nan@2.5.1 
        └─┬ prebuild-install@2.1.0 
          └─┬ tar-fs@1.15.0
            └─┬ tar-stream@1.5.2
              └─┬ bl@1.2.0 
                └── readable-stream@2.2.2 

Exception thrown by PacketStream substream end handler Error: unexpected end of parent stream
    at PacketStream.destroy (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:68:7)
    at PacketStream.write (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:121:41)
    at source (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:43:24)
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-goodbye/endable.js:6:7
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at source (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-pair/index.js:21:7)
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:7:11
    at Array.forEach (native)
    at abortAll (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:6:7)
Error: unexpected end of parent stream
    at PacketStream.destroy (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:68:7)
    at PacketStream.write (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:121:41)
    at source (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:43:24)
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-goodbye/endable.js:6:7
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-through/index.js:31:16
    at source (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-pair/index.js:21:7)
    at /home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:7:11
    at Array.forEach (native)
    at abortAll (/home/sww/.npm-global/lib/node_modules/scuttlebot/node_modules/pull-cat/index.js:6:7)
```

Meanwhile, `sbot` crashes:

```
[sww@figure8 ~]$ sbot server
Loading plugins from /home/sww/.ssb/node_modules
Log level: notice
fs.js:871
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/tmp/ssb-links/node_modules'
    at Object.fs.readdirSync (fs.js:871:18)
    at ChildProcess.<anonymous> (/home/sww/.npm-global/lib/node_modules/scuttlebot/plugins/plugins.js:122:29)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by clehner** [comment]
Looks like a bug in the plugins.install rpc method - maybe a race condition where the node_modules directory is not ready after the internal npm install command completes.

I suggest trying to install the plugins into place manually. I think this should do it:

  cd ~/.ssb
  npm i ssb-links ssb-query ssb-fulltext

Then with sbot running:

  sbot plugins.enable ssb-links
  sbot plugins.enable ssb-query
  sbot plugins.enable ssb-fulltext

Then restart sbot.

**Comment by noffle** [comment]
That did the trick -- thank you @cel.
