### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by DeveloppSoft** [ssbc/patchbay#95]
Hi,
I installed patchbay using the "official" instructions, everything is working correctly.

Unfortunately, when I run the tests, it failed, here is the trace:
```
eliott@tux:~/Documents/Blockchain/ssbc/patchbay$ npm run test

> patchbay@6.10.3 test /home/eliott/Documents/Blockchain/ssbc/patchbay
> browserify modules_*/index.test.js | tape-run

{ public: { v4: undefined, v6: undefined },
  private: { v4: undefined, v6: undefined } }
error loading sodium bindings: Cannot find module 'sodium-prebuilt/build/Release/sodium'
falling back to javascript version.
TypeError: fs.existsSync is not a function
    at Object.<anonymous> (file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:9267:8)
    at Object.123.fs (file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:9273:4)
    at s (file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:1:262)
    at file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:1:313
    at Object.<anonymous> (file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:3228:16)
    at Object.58.../h (file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:3479:4)
    at s (file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:1:262)
    at file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:1:313
    at Object.46../app (file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:2509:11)
    at s (file:///home/eliott/Documents/Blockchain/ssbc/patchbay/.source.1488655721855.html:1:262)

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! patchbay@6.10.3 test: `browserify modules_*/index.test.js | tape-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the patchbay@6.10.3 test script 'browserify modules_*/index.test.js | tape-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the patchbay package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify modules_*/index.test.js | tape-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs patchbay
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls patchbay
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eliott/Documents/Blockchain/ssbc/patchbay/npm-debug.log
eliott@tux:~/Documents/Blockchain/ssbc/patchbay$ cat ./npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle patchbay@6.10.3~pretest: patchbay@6.10.3
6 silly lifecycle patchbay@6.10.3~pretest: no script for pretest, continuing
7 info lifecycle patchbay@6.10.3~test: patchbay@6.10.3
8 verbose lifecycle patchbay@6.10.3~test: unsafe-perm in lifecycle true
9 verbose lifecycle patchbay@6.10.3~test: PATH: /usr/share/npm/bin/node-gyp-bin:/home/eliott/Documents/Blockchain/ssbc/patchbay/node_modules/.bin:/home/eliott/bin:/home/eliott/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle patchbay@6.10.3~test: CWD: /home/eliott/Documents/Blockchain/ssbc/patchbay
11 silly lifecycle patchbay@6.10.3~test: Args: [ '-c', 'browserify modules_*/index.test.js | tape-run' ]
12 silly lifecycle patchbay@6.10.3~test: Returned: code: 1  signal: null
13 info lifecycle patchbay@6.10.3~test: Failed to exec test script
14 verbose stack Error: patchbay@6.10.3 test: `browserify modules_*/index.test.js | tape-run`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid patchbay@6.10.3
16 verbose cwd /home/eliott/Documents/Blockchain/ssbc/patchbay
17 error Linux 4.4.0-62-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error patchbay@6.10.3 test: `browserify modules_*/index.test.js | tape-run`
22 error Exit status 1
23 error Failed at the patchbay@6.10.3 test script 'browserify modules_*/index.test.js | tape-run'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the patchbay package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     browserify modules_*/index.test.js | tape-run
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs patchbay
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls patchbay
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I can see here some infos:
  - it cannot load the `sodium bindings`, maybe because I need to install something else
  - it seems that something is calling `fs.existsSync` as a function

The following error (extracted from the previous logs) might help:
```
14 verbose stack Error: patchbay@6.10.3 test: `browserify modules_*/index.test.js | tape-run`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

PS: I know, scuttlebot/patchbay isn't a blockchain :smile:

**Comment by dominictarr** [comment]
hmm, it looks like browserify doesn't work because something is using `fs.existsSync` which is not available in browserify... I think that is caused by electron in this line: https://github.com/ssbc/patchbay/blame/master/modules_core/tabs.js#L5

this would break the lite client too, @mixmix

**Comment by DeveloppSoft** [comment]
I can confirm that the lite client is broken (the source code is generated but the browser displays only a blank page).

**Comment by mixmix** [comment]
You're probably right about that line breaking things @dominictarr . 
I'm happy for that to be removed if it's important for someone.

I'm not sure anyone is dev'ing it at the moment. Note that the newer version to patchbay I'm building doens't have the lite-client in mind. I'm of the opinion that should be built seperately, so that client can be good at what they do and not comprimising. This will also strengthen the eco-system and hone patchcore and sharing of depject modules

**Comment by dominictarr** [comment]
hmm, the best solution would be to move all the things that use electron into a separate depject module, that is then merged in. That would make it easy to disable.

**Comment by dominictarr** [comment]
also this might be useful: https://www.npmjs.com/package/is-electron

**Comment by mixmix** [comment]
I'm going to leave this for the moment.

If it's a big deal, I'm happy to do a quick fix - just go in and comment some stuff out.

**Comment by evbogue** [comment]
I haven't tried Patchbay in awhile, does this mean Patchbay doesn't support the lite client anymore?

**Comment by dominictarr** [comment]
it means it's broken right now

**Comment by evbogue** [comment]
Let's fix it.
