### ISSUE TITLE
Can't get 7.1.0 to start properly

### ISSUE THREAD

**Issue by AljoschaMeyer** [ssbc/patchbay#99]
`electron index.js` outputs the following. The process does not crash, but it never opens a window.

```
aljoscha@aljoscha-laptop ~/p/s/patchbay> npm start
> picknmix@7.1.0 start /home/aljoscha/projects/scuttleverse/patchbay
> electron index.js
App threw an error during load
ReferenceError: window is not defined
    at Object.<anonymous> (/home/aljoscha/projects/scuttleverse/patchbay/node_modules/pull-scroll/index.js:6:23)
    at Object.<anonymous> (/home/aljoscha/projects/scuttleverse/patchbay/node_modules/pull-scroll/index.js:109:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/aljoscha/projects/scuttleverse/patchbay/app/html/page/channel.js:3:18)
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: window is not defined
    at Object.<anonymous> (/home/aljoscha/projects/scuttleverse/patchbay/node_modules/pull-scroll/index.js:6:23)
    at Object.<anonymous> (/home/aljoscha/projects/scuttleverse/patchbay/node_modules/pull-scroll/index.js:109:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/aljoscha/projects/scuttleverse/patchbay/app/html/page/channel.js:3:18)
(node:31256) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
```

**Comment by AljoschaMeyer** [comment]
Ok, just ignore this (#98)
